# Generated by Django 5.1.1 on 2024-09-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_restaurant_phone_alter_restaurant_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
    ]
